using System;
using System.Collections.Generic;
using System.Globalization;

namespace BGCOP.CAVTOP.BUSINESSLAYER
{
	public class ModulosSoftware
	{
		public List<string> ListaModulos = new List<string>();

		public ModulosSoftware()
		{
			int num = 0;
			int num1 = num + 1;
			int num2 = num;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 1. Tipos de Identificacion"));
			int num3 = num1;
			num1 = num3 + 1;
			int num4 = num3;
			this.ListaModulos.Add(string.Concat(num4.ToString(CultureInfo.InvariantCulture), " 2. Maestro de Cargos"));
			int num5 = num1;
			num1 = num5 + 1;
			int num6 = num5;
			this.ListaModulos.Add(string.Concat(num6.ToString(CultureInfo.InvariantCulture), " 3. Maestro de Estados"));
			int num7 = num1;
			num1 = num7 + 1;
			int num8 = num7;
			this.ListaModulos.Add(string.Concat(num8.ToString(CultureInfo.InvariantCulture), " 4. Maestro de Empresas"));
			int num9 = num1;
			num1 = num9 + 1;
			int num10 = num9;
			this.ListaModulos.Add(string.Concat(num10.ToString(CultureInfo.InvariantCulture), " 5. Maestro de Divisiones"));
			int num11 = num1;
			num1 = num11 + 1;
			int num12 = num11;
			this.ListaModulos.Add(string.Concat(num12.ToString(CultureInfo.InvariantCulture), " 6. Maestro de Empleados"));
			int num13 = num1;
			num1 = num13 + 1;
			int num14 = num13;
			this.ListaModulos.Add(string.Concat(num14.ToString(CultureInfo.InvariantCulture), " 7. Maestro Marcas Vehiculos"));
			int num15 = num1;
			num1 = num15 + 1;
			int num16 = num15;
			this.ListaModulos.Add(string.Concat(num16.ToString(CultureInfo.InvariantCulture), " 8. Maestro Tipos Vehiculo"));
			int num17 = num1;
			num1 = num17 + 1;
			int num18 = num17;
			this.ListaModulos.Add(string.Concat(num18.ToString(CultureInfo.InvariantCulture), " 9. Maestro de Modelos Vehiculo"));
			int num19 = num1;
			num1 = num19 + 1;
			int num20 = num19;
			this.ListaModulos.Add(string.Concat(num20.ToString(CultureInfo.InvariantCulture), " 10. Asignacion Vehiculos Empleado"));
			int num21 = num1;
			num1 = num21 + 1;
			int num22 = num21;
			this.ListaModulos.Add(string.Concat(num22.ToString(CultureInfo.InvariantCulture), " 11. Maestro de Parqueaderos"));
			int num23 = num1;
			num1 = num23 + 1;
			int num24 = num23;
			this.ListaModulos.Add(string.Concat(num24.ToString(CultureInfo.InvariantCulture), " 12. Asignacion de Parqueos"));
			int num25 = num1;
			num1 = num25 + 1;
			int num26 = num25;
			this.ListaModulos.Add(string.Concat(num26.ToString(CultureInfo.InvariantCulture), " 13. Maestro de Horarios"));
			int num27 = num1;
			num1 = num27 + 1;
			int num28 = num27;
			this.ListaModulos.Add(string.Concat(num28.ToString(CultureInfo.InvariantCulture), " 14. Maestro de Tarjetas"));
			int num29 = num1;
			num1 = num29 + 1;
			int num30 = num29;
			this.ListaModulos.Add(string.Concat(num30.ToString(CultureInfo.InvariantCulture), " 15. Visitas Programadas"));
			int num31 = num1;
			num1 = num31 + 1;
			int num32 = num31;
			this.ListaModulos.Add(string.Concat(num32.ToString(CultureInfo.InvariantCulture), " 16. Visitantes"));
			int num33 = num1;
			num1 = num33 + 1;
			int num34 = num33;
			this.ListaModulos.Add(string.Concat(num34.ToString(CultureInfo.InvariantCulture), " 17. Usuarios"));
			int num35 = num1;
			num1 = num35 + 1;
			int num36 = num35;
			this.ListaModulos.Add(string.Concat(num36.ToString(CultureInfo.InvariantCulture), " 18. Roles"));
			int num37 = num1;
			num1 = num37 + 1;
			int num38 = num37;
			this.ListaModulos.Add(string.Concat(num38.ToString(CultureInfo.InvariantCulture), " 19. Liberar Parqueaderos"));
			int num39 = num1;
			num1 = num39 + 1;
			int num40 = num39;
			this.ListaModulos.Add(string.Concat(num40.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num41 = num1;
			num1 = num41 + 1;
			int num42 = num41;
			this.ListaModulos.Add(string.Concat(num42.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num43 = num1;
			num1 = num43 + 1;
			int num44 = num43;
			this.ListaModulos.Add(string.Concat(num44.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num45 = num1;
			num1 = num45 + 1;
			int num46 = num45;
			this.ListaModulos.Add(string.Concat(num46.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num47 = num1;
			num1 = num47 + 1;
			int num48 = num47;
			this.ListaModulos.Add(string.Concat(num48.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num49 = num1;
			num1 = num49 + 1;
			int num50 = num49;
			this.ListaModulos.Add(string.Concat(num50.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num51 = num1;
			num1 = num51 + 1;
			int num52 = num51;
			this.ListaModulos.Add(string.Concat(num52.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num53 = num1;
			num1 = num53 + 1;
			int num54 = num53;
			this.ListaModulos.Add(string.Concat(num54.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num55 = num1;
			num1 = num55 + 1;
			int num56 = num55;
			this.ListaModulos.Add(string.Concat(num56.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num57 = num1;
			num1 = num57 + 1;
			int num58 = num57;
			this.ListaModulos.Add(string.Concat(num58.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num59 = num1;
			num1 = num59 + 1;
			int num60 = num59;
			this.ListaModulos.Add(string.Concat(num60.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num61 = num1;
			num1 = num61 + 1;
			int num62 = num61;
			this.ListaModulos.Add(string.Concat(num62.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num63 = num1;
			num1 = num63 + 1;
			int num64 = num63;
			this.ListaModulos.Add(string.Concat(num64.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num65 = num1;
			num1 = num65 + 1;
			int num66 = num65;
			this.ListaModulos.Add(string.Concat(num66.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num67 = num1;
			num1 = num67 + 1;
			int num68 = num67;
			this.ListaModulos.Add(string.Concat(num68.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num69 = num1;
			num1 = num69 + 1;
			int num70 = num69;
			this.ListaModulos.Add(string.Concat(num70.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num71 = num1;
			num1 = num71 + 1;
			int num72 = num71;
			this.ListaModulos.Add(string.Concat(num72.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num73 = num1;
			num1 = num73 + 1;
			int num74 = num73;
			this.ListaModulos.Add(string.Concat(num74.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num75 = num1;
			num1 = num75 + 1;
			int num76 = num75;
			this.ListaModulos.Add(string.Concat(num76.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num77 = num1;
			num1 = num77 + 1;
			int num78 = num77;
			this.ListaModulos.Add(string.Concat(num78.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num79 = num1;
			num1 = num79 + 1;
			int num80 = num79;
			this.ListaModulos.Add(string.Concat(num80.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num81 = num1;
			num1 = num81 + 1;
			int num82 = num81;
			this.ListaModulos.Add(string.Concat(num82.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num83 = num1;
			num1 = num83 + 1;
			int num84 = num83;
			this.ListaModulos.Add(string.Concat(num84.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num85 = num1;
			num1 = num85 + 1;
			int num86 = num85;
			this.ListaModulos.Add(string.Concat(num86.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num87 = num1;
			num1 = num87 + 1;
			int num88 = num87;
			this.ListaModulos.Add(string.Concat(num88.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num89 = num1;
			num1 = num89 + 1;
			int num90 = num89;
			this.ListaModulos.Add(string.Concat(num90.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num91 = num1;
			num1 = num91 + 1;
			int num92 = num91;
			this.ListaModulos.Add(string.Concat(num92.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num93 = num1;
			num1 = num93 + 1;
			int num94 = num93;
			this.ListaModulos.Add(string.Concat(num94.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num95 = num1;
			num1 = num95 + 1;
			int num96 = num95;
			this.ListaModulos.Add(string.Concat(num96.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num97 = num1;
			num1 = num97 + 1;
			int num98 = num97;
			this.ListaModulos.Add(string.Concat(num98.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num99 = num1;
			num1 = num99 + 1;
			int num100 = num99;
			this.ListaModulos.Add(string.Concat(num100.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			num1 = 0;
		}
	}
}